# tanuh.mk — build automation for the TANUH HealthForge edge-model flavour.
#
# Two-command flow on a TANUH developer's machine:
#   make tanuh-setup     # one-time: generate signing keystore
#   make tanuh-apk       # per-build: encrypt model → assemble signed APK
#
# Plaintext model: tools/edge-model/source/<TANUH_MODEL_KEY>.tflite (gitignored)
# Encrypted output: packages/openchs-android/android/app/src/tanuh/assets/models/
#                   {<TANUH_MODEL_KEY>.bin, registry.json}    (gitignored)
# Signed APK:       packages/openchs-android/android/app/build/outputs/apk/tanuh/release/app-tanuh-release.apk
#
# See tools/edge-model/README.md for the full documentation.

# Override on the command line: TANUH_MODEL_KEY=oral-cancer-v2 make tanuh-apk
TANUH_MODEL_KEY ?= oral-cancer-v1
TANUH_MODEL_SRC := tools/edge-model/source/$(TANUH_MODEL_KEY).tflite
TANUH_OUT_DIR   := packages/openchs-android/android/app/src/tanuh/assets/models
TANUH_OVERRIDE  := tools/edge-model/sample-override.json
TANUH_KEYSTORE  := tanuh-release-key.keystore

tanuh-setup: ## One-time: generate the tanuh release keystore.
	@if [ -f "$(TANUH_KEYSTORE)" ]; then \
		echo "Keystore already exists at $(TANUH_KEYSTORE) — skipping. Delete it first to regenerate."; \
		exit 0; \
	fi
	@echo "Generating tanuh release keystore. You will be prompted for passwords and DN."
	@keytool -genkeypair -v \
		-keystore $(TANUH_KEYSTORE) \
		-alias tanuh \
		-keyalg RSA -keysize 2048 \
		-validity 10000
	@echo ""
	@echo "Keystore created. Set these env vars in your shell before running 'make tanuh-apk':"
	@echo "  export tanuh_KEYSTORE_PASSWORD='<the keystore password you just chose>'"
	@echo "  export tanuh_KEY_PASSWORD='<the key password you just chose>'"
	@echo "  export tanuh_KEY_ALIAS='tanuh'"

tanuh-encrypt: ## Encrypt the plaintext model and emit registry.json.
	@if [ ! -f "$(TANUH_MODEL_SRC)" ]; then \
		echo "ERROR: $(TANUH_MODEL_SRC) not found."; \
		echo "Drop your plaintext .tflite there (filename = TANUH_MODEL_KEY + .tflite)."; \
		echo "  cp /path/to/$(TANUH_MODEL_KEY).tflite tools/edge-model/source/"; \
		exit 1; \
	fi
	@mkdir -p $(TANUH_OUT_DIR)
	node tools/edge-model/encrypt-model.js \
		--in $(TANUH_MODEL_SRC) \
		--out-dir $(TANUH_OUT_DIR) \
		--model-key $(TANUH_MODEL_KEY) \
		--override $(TANUH_OVERRIDE) \
		--default-model

tanuh-apk: tanuh-encrypt ## Encrypt model + assemble signed tanuh release APK.
	@if [ ! -f "$(TANUH_KEYSTORE)" ]; then \
		echo "ERROR: $(TANUH_KEYSTORE) not found. Run 'make tanuh-setup' first."; \
		exit 1; \
	fi
	@if [ -z "$$tanuh_KEYSTORE_PASSWORD" ] || [ -z "$$tanuh_KEY_ALIAS" ]; then \
		echo "ERROR: signing env vars not set. Export tanuh_KEYSTORE_PASSWORD and tanuh_KEY_ALIAS."; \
		echo "(tanuh_KEY_PASSWORD is optional — modern keytool defaults to PKCS12 where it equals the keystore password.)"; \
		exit 1; \
	fi
	# Generate src/framework/Config.js with SERVER_URL from flavor_config.json (tanuh entry).
	# Without this, the app launches with no SERVER_URL configured and shows
	# "Server under maintenance" because /idp-details cannot be reached.
	$(MAKE) as_prod flavor=tanuh
	# Pick the metro bundler config (falls back to metro.config.generic.js for unknown flavours).
	$(MAKE) metro_config flavor=tanuh
	# KEY_STORE_PREFIX prepends to the keystore filename in build.gradle's file(...) lookup;
	# point it at repo root so the keystore generated by `make tanuh-setup` is found.
	cd packages/openchs-android/android; KEY_STORE_PREFIX="$(CURDIR)/" GRADLE_OPTS="$(if $(GRADLE_OPTS),$(GRADLE_OPTS),-Xmx1024m -Xms1024m)" ./gradlew assembleTanuhRelease --stacktrace
	@echo ""
	@echo "Signed APK: packages/openchs-android/android/app/build/outputs/apk/tanuh/release/app-tanuh-release.apk"

tanuh-clean: ## Remove the per-build encrypted blob and registry.json.
	rm -f $(TANUH_OUT_DIR)/*.bin $(TANUH_OUT_DIR)/registry.json
	@echo "Cleared $(TANUH_OUT_DIR)/"

# Debug-flavour iteration helpers — install + launch tanuh debug build via gradlew + adb.
# No encryption, no signing, no Metro release bundle. Requires `make run_packager` running
# in another terminal so the app can fetch the dev JS bundle.
#
# Use these for quick iteration on JS / native code without paying the cost of the signed
# release pipeline. To exercise the edge model, run `make tanuh-encrypt` first to populate
# src/tanuh/assets/models/; otherwise the debug build boots with no model registered.

run_app_tanuh: ## Install + launch tanuh debug build, prod backend.
	$(MAKE) as_prod flavor=tanuh
	$(MAKE) _run_app flavor=tanuh

run_app_tanuh_dev: ## Install + launch tanuh debug build, prod backend with dev menu.
	$(MAKE) as_prod_dev flavor=tanuh
	$(MAKE) _run_app flavor=tanuh

# Hyphenated aliases matching the project's `run-app-*` convention.
run-app-tanuh: run_app_tanuh
run-app-tanuh-dev: run_app_tanuh_dev

.PHONY: tanuh-setup tanuh-encrypt tanuh-apk tanuh-clean run_app_tanuh run_app_tanuh_dev run-app-tanuh run-app-tanuh-dev
